### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by Sagatho123** [RadioShuttle/MQTTPushClient_iOS#1]
Hello is there something new to the client configuration?

today a got a Connection Refused alert in my AWS MQTT broker server.

this is my actual configuration:

URL: XXX.s1.eu.hivemq.cloud
port: 8883

i use user and password and it works in another MQTT clients.

**Comment by helmut64** [comment]
We believe it was a server outage, if the problem remains reopen this.
